/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-01-13 05:22:53 
*/
import { IContainer } from "./IContainer";

export interface IParametersArray {
}

export interface IParameter {
    parent: IContainer;
    readonly id: string;
    readonly name: string;
    readonly type: string;
    readonly value: string;
}
