/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-01-13 04:39:47 
*/

export interface IExtensionConfigurationSmartObject {
    Enabled: string;
    Extension: string;
    ViewOrForm: string;
    Type: string;
    Joins: any;
}

export interface IExtensionSmartObject {
    Name: string;
    Description: string;
    Type: string;
    Code: string;
    Enabled: string;
    Module_Url: string;
    initialiseCommand: string;
    JoinedSmartObjectName: string;
}

// export interface IExtensionSmartObjectImplemented extends IExtensionSmartObject {
//     initialiseCommandResult: any
//     usageCount: number
// }