/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-01-13 05:37:01 
*/

export interface ISerialisedSmartObjectBaseArrayFactory {
}

export interface ISmartObjectBase<T extends ISmartObjectBase<T>> {
    createFromData(data: any): void;
    createFromSerialisedData(serialisedData: string): void;
}
