
import { Grid, OptFilter,AlignType, VAlignType, ColumnOptions, SortingType } from "@alterspective-io/as-framework-material-design/supporting";
import { OptColumnExtended, OptColumnHeaderInfo, OptGridExtended } from "./interfaces";
import { IASK2DataTableSettings, DataGridExecutionActions, Expression, IASK2DataTableSettingsCustomMethodBinding } from "./settings";
// import { ColumnOptions, OptFilter, AlignType, VAlignType, Grid, SortingType } from "@alterspective-io/as-framework-material-design";

// let ASK2DataTableDefaultSettings: ASK2DataTableSettings = {
//   enabled: true,
//   // columns?: Columns;
//   data: [],
//   elevation: 0,
//   autoBindToViewControls: true,
//   autogeneratedColumnSettings: {
//     name: "",
//     width: "auto",
//     renderer: undefined,
//     editor: "text",
//     relations: undefined,
//     filter: "text",
//     resizable: true,
//     sortable: true,
//   },
//   currentRowDataK2Control: undefined,
//   saveK2Control: "Button Save Changes,current",
//   k2RuleForEachUpdated: "When Save Button is Clicked,current",
//   autoGenerateColumns: true,
//   k2RuleForEachCreated: "When Create Button is Clicked,current",
//   k2RuleForEachDeleted: "When Delete Button is Clicked,current",
//   optGrid: {
//     columns: [],
//     rowHeight: 52,
//     pageOptions: {
//       useClient: true,
//       perPage: 12,
//     },
//     rowHeaders: ["checkbox"],
//     scrollX: true,
//     scrollY: true,
//   },
// };

export class AS_K2_DataTable_Default_Column_Settings implements ColumnOptions
{

  name="";
  // width?: number | "auto" | undefined = "auto"
  renderer? = undefined
  editor?=undefined
  relations?=undefined
  filter?:Grid.FilterOptionType | OptFilter | undefined= "text"
  header?: string | undefined = undefined
  hidden?: boolean | undefined = false
  align?: AlignType | undefined = "left"
  valign?: VAlignType | undefined = "middle"
  minWidth?: number | undefined =undefined
  whiteSpace?: "pre" | "normal" | "nowrap" | "pre-wrap" | "pre-line" | undefined = "normal"
  ellipsis?: boolean | undefined = true 
  sortable?: boolean | undefined =true
  escapeHTML?: boolean | undefined = false
  validation? = undefined
  className?: string | undefined 
  disabled?: boolean | undefined = false
  ignored?: boolean | undefined = false
  copyOptions? = undefined;
  defaultValue? = undefined;
  resizable?: boolean | undefined = true
  formatter? = undefined;
  sortingType?:SortingType | undefined = "asc"
  onBeforeChange? = undefined;
  onAfterChange? = undefined;
  comparator? = undefined;
  rowSpan?: boolean | undefined = false;
  
}

export class AS_OptGrid_Header_Column_Info_Default implements OptColumnHeaderInfo
{
  name: string = ""
  align?: AlignType | undefined = "left"
  valign?:VAlignType  ="bottom" 
  
}

export class AS_K2_DataTable_Default_Settings implements IASK2DataTableSettings
{
  k2control_to_bind_rowData: string | null | undefined;
  customBinding: { [field: string]: string; } | null | undefined;
  customGridMethodBindings: IASK2DataTableSettingsCustomMethodBinding[] | null | undefined;
  customStyle: string | string[] | null | undefined;
  sampleData: string | null | undefined;
  execute_grid_method_deleteSelectedRow_on: string | null | undefined;
  k2_rule_to_execute_for_each_updated: string | null | undefined;
  k2_rule_to_execute_for_each_created: string | null | undefined;
  k2_rule_to_execute_for_each_deleted: string | null | undefined;
  k2_rule_to_execute_for_each_checked: string | null | undefined;
  k2_rule_to_execute_for_double_click: string | null | undefined;
  theme: Grid.PresetOptions | null | undefined;

  // applySortAndFilterToNewLine: boolean = false
  expressions: Expression[] | undefined;
  enabled= true
  data= []
  elevation= 0
 minHeight=350
  autoBindToViewControls= true
  autoBindToViewName= "current";
  columnDefaults: OptColumnExtended = new AS_K2_DataTable_Default_Column_Settings()
  k2control_to_bind_rowIndex: undefined
  execute_grid_method_saveModifiedData_on= "Button Save Changes,current"
  execute_grid_method_runForEachChecked_on="Button For Each Checked,current"
  execute_grid_method_appendNewRow_on="Button Add New Row,current"
  k2RuleForEachUpdated= "When Save Button is Clicked,current"
  execute_grid_method_export_on="Button Export,current"
  exportSettings="Text Area Export Settings,current"
  autoGenerateColumns= true
  k2RuleForEachCreated= "When Create Button is Clicked,current"
  k2RuleForEachDeleted= "When Delete Button is Clicked,current"
  k2RuleForEachChecked="For Each Checked Item,current"
  k2_rule_to_execute_for_focus_changed="When the View executed List item click,current"
  default_grid_action_for_each_checked_item=DataGridExecutionActions.none
  optGrid: OptGridExtended = {
    columns: [],
    columnOptions: {
      minWidth: 100,
      frozenCount: undefined,
      frozenBorderWidth: undefined,
      resizable: true
    },
  
    header:
    {
       align:"right",
       columns: [],
       valign:"top"
      //  height:300 - autoset by style sheet but can be overriden here
      // columns:
      // [
       
      // ]
       
    },
    rowHeight: "auto",
    draggable: false,
    heightResizable:false,
    width:"auto",
    pageOptions: {
      useClient: true,
      perPage: 12,
    },
    // rowHeaders: ["checkbox"],
    scrollX: true,
    scrollY: false,
  }

}

// export { ASK2DataTableDefaultSettings };
