// Generated by https://quicktype.io

export interface IViewHiddenHash {

    "bc17fb1b-163b-40de-a7ba-23f958bd33fe_b9a69149-6c0e-4caa-b320-6b2cd0f802cb": Bc17Fb1B163B40DeA7Ba23F958Bd33FeB9A691496C0E4CaaB3206B2Cd0F802Cb[];
    "56ddd870-323a-4cfe-9e42-65480297beb5_88931d0c-2e3a-40c9-960b-4c151b144dfc": The56Ddd870323A4Cfe9E4265480297Beb588931D0C2E3A40C9960B4C151B144Dfc[];
    "null_00000000-0000-0000-0000-000000000000":                                 Null00000000000000000000000000000000[];
    "79e20584-bacf-41fb-b13e-da030eee3aeb_a4f8f1ef-eb47-e870-fbb1-194dad3436b2": The79_E20584Bacf41_FbB13EDa030Eee3Aeb[];
    "79e20584-bacf-41fb-b13e-da030eee3aeb_5b3e4cdd-7bd3-b500-47be-4cca82c75100": The79_E20584Bacf41_FbB13EDa030Eee3Aeb[];
    "69d6d3a0-aabb-4e7e-9dbb-a6c4ab0d270f_fc211358-4ce8-841e-73dc-3eb28fec31be": The69_D6D3A0AABB4_E7E9_DbbA6C4Ab0D270FFc2113584_Ce8841_E73_Dc3_Eb28Fec31Be[];
    "9b32ed73-28b9-4738-af24-8c41ccc1fd43_44aeb7ad-512d-db19-c44a-23dcbbacc69f": The69_D6D3A0AABB4_E7E9_DbbA6C4Ab0D270FFc2113584_Ce8841_E73_Dc3_Eb28Fec31Be[];
    "89a0784f-7611-4bb9-8696-636c29f8323f_8522fb93-01cb-ef2b-61ab-4f158f9f2da7": The89_A0784F76114_Bb98696636_C29F8323F[];
    "79e20584-bacf-41fb-b13e-da030eee3aeb_a91a1956-cf9b-017b-30ce-19faea0a7a27": The79_E20584Bacf41_FbB13EDa030Eee3Aeb[];
    "89a0784f-7611-4bb9-8696-636c29f8323f_17070654-7616-ba9a-fa07-11f5de5fe9a8": The89_A0784F76114_Bb98696636_C29F8323F[];
    "79e20584-bacf-41fb-b13e-da030eee3aeb_1d565bfc-9d22-e577-1c60-5b337dbaf0b4": The79_E20584Bacf41_FbB13EDa030Eee3Aeb[];
}

export interface The56Ddd870323A4Cfe9E4265480297Beb588931D0C2E3A40C9960B4C151B144Dfc {
    parentid:    string;
    parenttype:  string;
    contextid:   string;
    contexttype: string;
    fields:      The56Ddd870323A4Cfe9E4265480297Beb588931D0C2E3A40C9960B4C151B144DfcFields;
    state:       string;
}

export interface The56Ddd870323A4Cfe9E4265480297Beb588931D0C2E3A40C9960B4C151B144DfcFields {
    Theme: PuneHedgehog;
}

export interface PuneHedgehog {
    cleared: boolean;
}

export interface The69_D6D3A0AABB4_E7E9_DbbA6C4Ab0D270FFc2113584_Ce8841_E73_Dc3_Eb28Fec31Be {
    counter:     string;
    name:        string;
    parentid:    string;
    join:        string;
    contexttype: string;
    contextid:   string;
    instanceid:  string;
    pagenumber?: string;
    parenttype:  string;
    fields:      { [key: string]: Field };
    state:       string;
}

export interface Field {
    value: string;
}

export interface The79_E20584Bacf41_FbB13EDa030Eee3Aeb {
    parentid:    string;
    parenttype:  string;
    contextid:   string;
    contexttype: string;
    fields:      The79E20584Bacf41FbB13EDa030Eee3Aeb1D565Bfc9D22E5771C605B337Dbaf0B4Fields;
    state:       string;
}

export interface The79E20584Bacf41FbB13EDa030Eee3Aeb1D565Bfc9D22E5771C605B337Dbaf0B4Fields {
    TextRequiredContol: PuneHedgehog;
    TextUniqueControl:  PuneHedgehog;
    YesNoControl:       Field;
    TimeControl:        PuneHedgehog;
    NumberControl:      PuneHedgehog;
    MultiValueControl:  Field;
    MemoControl:        PuneHedgehog;
    ImageControl:       PuneHedgehog;
    HyperLinkControl:   PuneHedgehog;
    GUIDControl:        PuneHedgehog;
    FileControl:        PuneHedgehog;
    DecimalControl:     PuneHedgehog;
    DateTimeControl:    PuneHedgehog;
    DateControl:        PuneHedgehog;
    TextControl:        PuneHedgehog;
    Date:               PuneHedgehog;
    Last_Name:          PuneHedgehog;
    First_Name:         PuneHedgehog;
    ID:                 PuneHedgehog;
}

export interface The89_A0784F76114_Bb98696636_C29F8323F {
    parentid:    string;
    parenttype:  string;
    contextid:   string;
    contexttype: string;
    fields:      The89A0784F76114Bb98696636C29F8323F170706547616Ba9AFa0711F5De5Fe9A8Fields;
    state:       string;
    counter?:    string;
    name?:       string;
    join?:       string;
    instanceid?: string;
    controlid?:  string;
}

export interface The89A0784F76114Bb98696636C29F8323F170706547616Ba9AFa0711F5De5Fe9A8Fields {
    Name?:                          Name;
    TextRequiredContol?:            PuneHedgehog;
    TextUniqueControl?:             PuneHedgehog;
    YesNoControl?:                  Field;
    TimeControl?:                   PuneHedgehog;
    NumberControl?:                 PuneHedgehog;
    MultiValueControl?:             Field;
    MemoControl?:                   PuneHedgehog;
    ImageControl?:                  PuneHedgehog;
    HyperLinkControl?:              PuneHedgehog;
    GUIDControl?:                   PuneHedgehog;
    FileControl?:                   PuneHedgehog;
    DecimalControl?:                PuneHedgehog;
    DateTimeControl?:               PuneHedgehog;
    DateControl?:                   PuneHedgehog;
    TextControl?:                   PuneHedgehog;
    Date?:                          PuneHedgehog;
    Last_Name?:                     PuneHedgehog;
    First_Name?:                    Field;
    ID?:                            PuneHedgehog;
    Framework_Script_Location?:     Field;
    Version?:                       Field;
    Framework_Load_Command?:        Field;
    Script_To_Execute?:             Field;
    SignalR_Notifications?:         Field;
    SignalR_Client_Javascript_URL?: Field;
    Active_Setting?:                Field;
}

export interface Name {
    cleared?: boolean;
    value?:   string;
}

export interface Bc17Fb1B163B40DeA7Ba23F958Bd33FeB9A691496C0E4CaaB3206B2Cd0F802Cb {
    parentid:    string;
    parenttype:  string;
    contextid:   string;
    contexttype: string;
    fields:      Bc17Fb1B163B40DeA7Ba23F958Bd33FeB9A691496C0E4CaaB3206B2Cd0F802CbFields;
    state:       string;
}

export interface Bc17Fb1B163B40DeA7Ba23F958Bd33FeB9A691496C0E4CaaB3206B2Cd0F802CbFields {
    Script_To_Execute?:             Field;
    Active_Setting?:                Field;
    Name?:                          Field;
    Framework_Script_Location?:     Field;
    Version?:                       Field;
    Framework_Load_Command?:        Field;
    SignalR_Client_Javascript_URL?: Field;
    SignalR_Notifications?:         Field;
    HttpResponseCode?:              PuneHedgehog;
    Control_Name?:                  PuneHedgehog;
    ID?:                            PuneHedgehog;
}

export interface Null00000000000000000000000000000000 {
    parentid:   string;
    parenttype: string;
    method:     boolean;
    parameters: Parameters;
    state:      string;
}

export interface Parameters {
    userid:    Field;
    groupname: Field;
}
